# SENSORS
sensor:
## Huawei Solar PEES - Energy Sensors
  - platform: integration
    source: sensor.power_battery_charge
    name: "Energy Battery Charge"
    unique_id: energy_battery_charge
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.power_battery_charge_grid
    name: "Energy Battery Charge Grid"
    unique_id: energy_battery_charge_grid
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.power_battery_charge_yield
    name: "Energy Battery Charge Yield"
    unique_id: energy_battery_charge_yield
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.power_battery_discharge
    name: "Energy Battery Discharge"
    unique_id: energy_battery_discharge
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.power_import
    name: "Energy Import"
    unique_id: energy_import
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.power_export
    name: "Energy Export"
    unique_id: energy_export
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.power_house_load
    name: "Energy House Load"
    unique_id: energy_house_load
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.power_house_load_grid
    name: "Energy House Load Grid"
    unique_id: energy_house_load_grid
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.power_house_load_yield
    name: "Energy House Load Yield"
    unique_id: energy_house_load_yield
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.inverter_input_power_1
    name: "Energy Yield #1"
    unique_id: energy_yield_1
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    source: sensor.inverter_input_power_2
    name: "Energy Yield #2"
    unique_id: energy_yield_2
    round: 6
    unit_prefix: k
    unit_time: h
    method: left
